In [15]:
import numpy as np
import pandas as pd
import io
import requests
# Import cufflinks for visualization
import cufflinks as cf
cf.set_config_file(offline=True)

In [2]:
TOTAL_SEATS = 650
MAJORITY = 326

In [3]:
df = pd.read_html('https://en.wikipedia.org/wiki/House_of_Commons_of_the_United_Kingdom')[2]
# df

In [4]:
df.columns = df.columns.to_flat_index()

df = df[df.columns[1:]]

df.columns = ["party", "members_2019", "members_2024", "delta"]

df.loc[1].party = "Labour"
df.loc[12].party = "Reform"

df.loc[8].members_2019 = 0
df.loc[8].members_2024 = 2

df.loc[11].members_2019 = 0
df.loc[11].members_2024 = 1

df.loc[14].members_2019 = 0
df.loc[14].members_2024 = 17

df.drop(index=[16, 17, 18], inplace=True)

df.members_2024 = df.members_2024.apply(lambda x: int(x))
df.members_2019 = df.members_2019.apply(lambda x: int(x))
                      
df["delta"] = df.members_2024 - df.members_2019
df.set_index("party", inplace=True)
df

                   members_2019  members_2024  delta
party
Conservative                365           344    -21
Labour                      202           205      3
SNP                          48            43     -5
Liberal Democrats            11            15      4
DUP                           8             7     -1
Sinn Féin                     7             7      0
Plaid Cymru                   4             3     -1
SDLP                          2             2      0
Alba                          0             2      2
Green (E&W)                   1             1      0
Alliance (NI)                 1             1      0
Workers Party                 0             1      1
Reform                        0             1      1
Speaker                       1             1      0
Independent                   0            17     17
Vacant                        0             0      0

In [5]:
exit_poll = {
    "Labour": 410,
    "Conservative": 131,
    "Liberal Democrats": 61,
    "Reform": 13,
    "SNP": 10
}

410
131
61
13

209
-241
53
13

current = {
    "Labour": 206,
    "Conservative": 345,
    "Liberal Democrats": 15,
    "Reform": 1,
    "SNP": 43
}


df["current"] = pd.Series(current)
df["exit_poll"] = pd.Series(exit_poll)
df["change"] = df.exit_poll - df.current
df.sort_values("exit_poll", ascending=False, inplace=True)

In [6]:
df.head()

,members_2019,members_2024,delta,current,exit_poll,change
party,,,,,,
Labour,202,205,3,206.0,410.0,204.0
Conservative,365,344,-21,345.0,131.0,-214.0
Liberal Democrats,11,15,4,15.0,61.0,46.0
Reform,0,1,1,1.0,13.0,12.0
SNP,48,43,-5,43.0,10.0,-33.0

In [14]:
df_res = pd.read_html('https://www.bbc.co.uk/news/election/2024/uk/results')[0]
# df_vote_share = pd.read_html('https://www.bbc.co.uk/news/election/2024/uk/results')[1]
# df_res_sco = pd.read_html('https://www.bbc.co.uk/news/election/2024/uk/results')[2]
# df_res_wal = pd.read_html('https://www.bbc.co.uk/news/election/2024/uk/results')[3]

# df_res = df_res_eng + df_res_ni + df_res_sco + df_res_wal
df_res.head()

              Party Vote share Change since 2019
0            Labour      48.3%             +4.3%
1         Reform UK      28.0%            +15.5%
2      Conservative      14.5%            −18.7%
3             Green       4.6%             +1.8%
4  Liberal Democrat       4.6%             −1.6%

In [8]:
pd.read_html("https://www.theguardian.com/politics/ng-interactive/2024/jul/04/"
"uk-general-election-results-2024-live-in-full")[0]

              Party  Seats  Change  Votes (%) Change (% pt)  Votes
0            Labour      2       0       48.3          +4.3  38867
1         Reform UK      0       0       28.0             -  22525
2      Conservative      0       0       14.5         -18.7  11635
3  Liberal Democrat      0       0        4.6          -1.5   3723
4             Green      0       0        4.6          +1.8   3683

In [9]:
pd.read_html("https://ig.ft.com/uk-general-election/2024/results/")[0]

Empty DataFrame
Columns: [Party, Seats won, Exit poll, Net seats, % of vote]
Index: []

In [10]:
.47*.51

0.2397

In [11]:
.47 * 11668/18847

0.29097256857855364

In [12]:
.51 * .47 * 11668/18847

0.14839600997506233

In [31]:
c = pd.read_csv("/Users/ammarakhtar/Downloads/electdata_2019.txt")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 53092: invalid continuation byte